#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := udp_client

VPATH = /home/niva/GitHub/esp32-bno055/components/bno055:/home/niva/GitHub/esp32-bno055/components/bno055/include

#include /home/niva/GitHub/esp32-bno055/components/bno055/component.mk
include $(IDF_PATH)/make/project.mk

